### PR TITLE
BUG FIX: $order->customer_user causes PHP Notice

### PR DESCRIPTION
**Pull request by eighty20results**

### CODE REVIEW

**Comment by contemplate** [comment]
I created a similar solution in [64](https://github.com/strangerstudios/pmpro-woocommerce/pull/64).

**Comment by ideadude** [comment]
Thanks to both of you. I'm going to merge this one just because $user_id seems like a better var name than $customer_id. I don't see any other material differences. @contemplate let me know if I'll miss something if I cancel #64 in favor of this one.

**Comment by ideadude** [comment]
Actually going to close this one too. Seems like another another PR fixed this.

**Comment by contemplate** [comment]
Haha I think I beat you to it as I figured mine overlapped with this as well as #90 which you already merged.

**Pull request closed without merging**
