### PR TITLE
Addon: Sell PmPro Discount Codes through WooCommerce

### PR DESCRIPTION
**Pull request by contemplate**
This new addition allows for a better Gift Membership experience through WooCommerce.
- Ability to select existing PMPro Discount Code to sell
- Unique 1-time-use copy of Discount Code created at purchase
- Ability to email new Member Gift Code to a Recipient or to Customer
- New Email Template created: gift_membership_code.html
- New Email Tag: !!gift_product!!  =>  Title of the Product
- New Email Tag: !!membership_gift_code!!  => Generated Gift Code

I know others wanted this functionality so hope it helps the community :)

### CODE REVIEW

**Comment by contemplate** [comment]
@strangerstudios what can I do to help get this implemented in the core plugin?

**Comment by strangerstudios** [comment]
Hey, this is awesome. Sorry I let this go for so long. I'll be taking a look over the next week or so. On quick inspection it looks "all good". I just want to get a smaller update out with the WC 2.1.2/3 fixes and then will pull this in and test it. Thanks!

**Comment by contemplate** [comment]
Sounds great.  Let me know if you have further questions.  I have this successfully running on 3 or 4 production sites.

**Comment by blackbizchamps** [comment]
Hi guys,

I would like to list the WOOCommerce invoices for these gift membership purchases in the invoices section of PMP member-accounts. Or alternatively, list the codes and corresponding gift recipients there, similar to how PMP codes are displayed there.

How might this be done?

Thanks!

**Comment by contemplate** [comment]
@strangerstudios I just noticed that my original code was adjusted to require the PMPro Gift Levels Addon also be active.  Why?  The code I wrote didn't need that plugin.

**Pull request merged**
